sugarcube-2:
    macros:
        liveblock:
            name: liveblock
            container: true
        update:
            name: update
            container: false
        pronoun:
            name: pronoun
            container: false
