sugarcube-2:
  macros:
    liveblock:
      name: liveblock
      container: true
    update:
      name: update
      container: false
    pronoun:
      name: pronoun
      container: false
    graveyard:
      name: graveyard
    date:
      name: date
    time12h:
      name: time12h
    time24hr:
      name: time24hr
    datetime:
      name: datetime
    addmins:
      name: addmins
    addhours:
      name: addhours
    adddays:
      name: adddays
    
      
