name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        # Two ways to do this
        # One have a local storyformats folder (Needs to have the latest format updated manually constantly)
        # Pull sugarcube story format and compile it with github actions (Preferred since bi manual uploads)

        steps:
            - uses: actions/checkout@v3

            - name: Use Go 1.13
              uses: actions/setup-go@v3
              with:
                  go-version: 1.13.x

            - name: Use Node
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Build Tweego
              run: |
                  go get github.com/tmedwards/tweego
                  export PATH=$PATH:$(go env GOPATH)/bin
                  npm ci
                  npm run build --if-present
            #- name: Build game
            #  run: |
            #      npm ci
            #      npm run build --if-present

            - name: Deploy to Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./dist
